---
output:
  pdf_document: default
  html_document: default
---
# Libraries

```{r warning=TRUE}
library(spatstat) 
library(reticulate) 
library(RColorBrewer) 
pd <- import("pandas")
library(readxl)
```

# Definition of input Data

```{r}
chains_to_investigate <- list("Chain 1" )
```

```{r}
investigation_scenario <- 2
```

# Read Data

## Window

```{r}
window = owin(c(0,1000), c(0,1000))
```

## Outbreak

Outbreak made with Diffusion Model:

```{r}
#outbreak_data <- pd$read_pickle(paste("C:\\Users\\srude\\Documents\\Dev Kram\\Toy Example Traceback Model\\Diffusion Model\\Outputs\\Outbreaks\\Scenario_", as.character(scenario), "\\Outbreak_Chain 1_10_0.pkl", sep = ""))
# outbreak_data <- pd$read_pickle("./Data/Outbreaks/Toy_Outbreak_10.pkl") 
# ppp_outbreak <- ppp(x=outbreak_data$x_centroid, y=outbreak_data$y_centroid, window = window)
```

Outbreak artificially made to test model:
```{r}
df_outbreak <- subset(read_excel("./Data/scenarios.xlsx", sheet = "Outbreak_Locations"), scenario == investigation_scenario)
```



```{r}
ppp_outbreak <- ppp(x = df_outbreak$case_x, y = df_outbreak$case_y, window = window ) 
ppp_outbreak <- rescale(ppp_outbreak, 1000, "km")
```

## Population Data


```{r}
no_of_cells <- 100 
population_per_cell <- subset(read_excel("./Data/scenarios.xlsx", sheet = "Population"), scenario == investigation_scenario)$population_per_cell
```


```{r}
# calculate number of cells per row
cells_per_row <- sqrt(no_of_cells)

# generate a sequence of coordinates for centroids
centroid_coords <- seq(50, by = 100, length.out = cells_per_row)

# generate all combinations of these coordinates
df_population <- expand.grid(x_centroid = centroid_coords, y_centroid = centroid_coords)

# assign population
df_population$population <- rep(population_per_cell, nrow(df_population))
```

```{r}
ppp_population <- ppp(x = df_population$x_centroid, y = df_population$y_centroid, window = window, marks = df_population$population)
ppp_population <- rescale(ppp_population, 1000, "km")
smo_population <- density(ppp_population, eps = 0.1, positive = TRUE, weights = marks(ppp_population)) 
```

```{r}
im_population <- smo_population
im_population <- eval.im(im_population / 100)
im_population <- eval.im(pmax(im_population, 1e-10))
```


```{r}
plot(im_population)
```

# Quadrature Scheme

```{r}
Q <- quadscheme(ppp_outbreak, eps = 0.1)
```

# Null Model

```{r}
fit0 <- ppm(Q ~ offset(log(im_population)))
print(fit0)
```

$$\lambda_0(u) = e^{-3.912}Z(u) = 0.02 Z(u)$$

# Shops Data
Private Computer
```{r eval=FALSE}
shops <- pd$read_pickle(paste("C:\\Users\\srude\\Documents\\Pattern Comparison Project\\Toy_Example\\Diffusion_Model\\Outputs\\Stores\\stores_", as.character(scenario), ".pkl", sep = ""))
```
Work Computer
```{r eval=FALSE}
shops <- pd$read_pickle(paste("C:\\Users\\Sandra.Rudeloff\\Documents\\Pattern Comparison Project\\Toy_Example\\Diffusion_Model\\Outputs\\Stores\\stores_", as.character(scenario), ".pkl", sep = ""))
```

```{r}
df_shops <- subset(read_excel("./Data/scenarios.xlsx", sheet = "Store_Locations"), scenario == investigation_scenario)
```


```{r}
ppp_shops <- ppp(x = df_shops$store_x, y = df_shops$store_y, window = window, marks = as.factor(df_shops$chain))
ppp_shops <- rescale(ppp_shops, 1000, "km")
```

# Alternative Model

```{r}
for (chain in chains_to_investigate) {
  #for (chain in levels(ppp_shops$marks)){
  print(chain)
  # Alternative Model 
  ppp_chosen <- subset(ppp_shops, marks == chain, drop = TRUE)
  ppp_chosen <- unmark(ppp_chosen)
  
  # plot  
    X <- layered(im_population, unmark(subset(ppp_shops, marks != chain, drop = TRUE)),ppp_chosen,ppp_outbreak)
  layerplotargs(X)[[1]] <- list(col = brewer.pal(n = 8, name = "Greys"), breaks = c(0, 1, 10, 50, 100, 150, 200, 250, 260))
  layerplotargs(X)[[2]] <- list(pch = 18, cex = 0.8, col = "#386f9c")
  layerplotargs(X)[[3]] <- list(pch = 18, cex = 1.5, col = "gold")
  layerplotargs(X)[[4]] <- list(pch = 20, col = "red2", cex = 1.5)
  plot(X, main = "Potential sources and cases", axes = TRUE,  xlim = c(0, 1), ylim = c(0, 1) )
  
  ls_all_raisins = list()
  for (i in 1:ppp_chosen$n)  {
    ls_all_raisins[i] =  paste0("log((1 +  abs(alpha) * (exp(-(abs(beta)) * ((x- ",ppp_chosen$x[i],")^2 + (y- ",ppp_chosen$y[i],")^2)))))")
  }
  
  str_all_raisins <- paste(ls_all_raisins, collapse = "+")     
  eval(parse(text = paste('raisin_func <- function(x, y, alpha, beta) {(' , str_all_raisins , ')}', sep = '')))
  
  fit1 <- ippm(Q ~ offset(log(im_population) + raisin_func),
               start = list(alpha = 5, beta = 15), nlm.args = list(stepmax = 1), gcontrol = glm.control(maxit = 1000)) # nlm.args = list(stepmax = 1, print.level = 2)
  print(paste("Alternative Model for ", chain))
  print(fit1)
  print(paste("Anova for ", chain))
  print(anova(fit0, fit1, test = "LRT"))
}
```


