---
output:
  pdf_document: default
---
# Libraries

```{r}
library(spatstat) 
library(reticulate) 
library(RColorBrewer) 
pd <- import("pandas")
```

# Definition of input Data

```{r}
chains_to_investigate <- list("Chain 1" )
```

```{r}
scenario <- 1
```

## Window

```{r}
window = owin(c(0,1000), c(0,1000))
```

## Outbreak
Outbreak artificially made to test model:

```{r}
ppp_outbreak <- ppp(x = c(750, 150, 50, 450, 50, 850, 850, 950, 50, 750), y = c(150, 250, 250, 450, 850, 150, 850, 150, 150, 850), window = window ) 
ppp_outbreak <- rescale(ppp_outbreak, 1000, "km")
```

## Population Data
uniform population of 5 in each cell (500 total)
```{r}
no_of_cells <- 100 
population_per_cell <- 5

# initialize an empty data.frame
df_population <- data.frame("population" = numeric(), "x_centroid" = numeric(), "y_centroid" = numeric())

# set values
y <- -50
x <- 50

for (i in 1:no_of_cells) {
  if (i %% 10 == 1) {
    y <- y + 100
    x <- 50
  }
  
  df_population[i, "y_centroid"] <- y
  df_population[i, "x_centroid"] <- x
  
  x <- x + 100
}

df_population$population <- rep(population_per_cell, nrow(df_population))
```

```{r}
ppp_population <- ppp(x = df_population$x_centroid, y = df_population$y_centroid, window = window, marks = df_population$population)
ppp_population <- rescale(ppp_population, 1000, "km")
smo_population <- density(ppp_population, eps = 0.1, positive = TRUE, weights = marks(ppp_population)) 
```

```{r}
im_population <- smo_population
im_population <- eval.im(im_population / 100)
im_population <- eval.im(pmax(im_population, 1e-10))
```

```{r}
plot(im_population)
```

# Quadrature Scheme

```{r}
Q <- quadscheme(ppp_outbreak, eps = 0.1)
```

# Null Model

```{r}
fit0 <- ppm(Q ~ offset(log(im_population)))
print(fit0)
```

$$\lambda_0(u) = e^{-3.912}Z(u) = 0.02 Z(u)$$

# Shops Data
```{r}
x_coord <- c(112, 823, 888, 105, 487)
y_coord <- c(198, 112, 846, 855, 537)
Chain <- rep("Chain 1", 5)

ID <- 1:length(x_coord)
df_shops <- data.frame(
  ID = ID,
  x_coord = x_coord,
  y_coord = y_coord,
  Chain = Chain,
  Gitter_ID = character(length(x_coord))
)
```


```{r}
shops <- df_shops
ppp_shops <- ppp(x = shops$x_coord, y = shops$y_coord, window = window, marks = as.factor(shops$Chain))
ppp_shops <- rescale(ppp_shops, 1000, "km")
```

# Alternative Model

```{r}

alpha_start <- 5
beta_start_values <- 1:25

for (chain in chains_to_investigate) {
  #for (chain in levels(ppp_shops$marks)){
  # print(chain)
  # Alternative Model 
  ppp_chosen <- subset(ppp_shops, marks == chain, drop = TRUE)
  ppp_chosen <- unmark(ppp_chosen)
  
  # plot  
    X <- layered(im_population, unmark(subset(ppp_shops, marks != chain, drop = TRUE)),ppp_chosen,ppp_outbreak)
  layerplotargs(X)[[1]] <- list(col = brewer.pal(n = 8, name = "Greys"), breaks = c(0, 1, 10, 50, 100, 150, 200, 250, 260))
  layerplotargs(X)[[2]] <- list(pch = 18, cex = 0.8, col = "#386f9c")
  layerplotargs(X)[[3]] <- list(pch = 18, cex = 1.5, col = "gold")
  layerplotargs(X)[[4]] <- list(pch = 20, col = "red2", cex = 1.5)
  plot(X, main = "Potential sources and cases", axes = TRUE,  xlim = c(0, 1), ylim = c(0, 1) )
  
  ls_all_raisins = list()
  for (i in 1:ppp_chosen$n)  {
    ls_all_raisins[i] =  paste0("log((1 +  abs(alpha) * (exp(-(abs(beta)) * ((x- ",ppp_chosen$x[i],")^2 + (y- ",ppp_chosen$y[i],")^2)))))")
  }
  
  str_all_raisins <- paste(ls_all_raisins, collapse = "+")     
  eval(parse(text = paste('raisin_func <- function(x, y, alpha, beta) {(' , str_all_raisins , ')}', sep = '')))
  
    

    for (beta_start in beta_start_values) {
    fit1 <- ippm(Q ~ offset(log(im_population) + raisin_func),
                 start = list(alpha = alpha_start, beta = beta_start), nlm.args = list(stepmax = 1), gcontrol = glm.control(maxit = 1000)) # nlm.args=list(stepmax=1, print.level=2)
    print(paste("Starting values: alpha = ", alpha_start, " beta = ", beta_start))
    print(paste("Alternative Model for ", chain))
    print(fit1)
    print(paste("Anova for ", chain))
    print(anova(fit0, fit1, test = "LRT"))
  }
}
```
